"use client";

import { useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import { Download, FileText, Loader2 } from "lucide-react";

function formatNumber(value) {
  const num = Number(value);
  if (!Number.isFinite(num)) return "-";
  return num.toLocaleString(undefined, { maximumFractionDigits: 4 });
}

function createCorrelationBars(doc, pairs, startY) {
  let y = startY;
  const left = 20;
  const labelWidth = 95;
  const barStart = left + labelWidth + 4;
  const barMax = 70;

  doc.setFontSize(11);
  doc.setTextColor(230, 230, 235);
  doc.text("Top Correlation Bars", left, y);
  y += 8;

  pairs.slice(0, 6).forEach((pair) => {
    const label = `${pair.feature_a} ↔ ${pair.feature_b}`;
    const abs = Math.min(1, Number(pair.abs_correlation || 0));
    const barWidth = barMax * abs;

    doc.setFontSize(9);
    doc.setTextColor(180, 185, 200);
    doc.text(label, left, y + 4);

    doc.setDrawColor(55, 65, 81);
    doc.setFillColor(30, 41, 59);
    doc.roundedRect(barStart, y, barMax, 5, 1, 1, "FD");

    doc.setFillColor(59, 130, 246);
    doc.roundedRect(barStart, y, barWidth, 5, 1, 1, "F");

    doc.setTextColor(120, 210, 255);
    doc.text(formatNumber(pair.correlation), barStart + barMax + 4, y + 4);
    y += 9;
  });

  return y;
}

function addWrappedText(doc, text, x, y, width, lineHeight = 5) {
  const lines = doc.splitTextToSize(text || "", width);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

export default function ReportsView({ data }) {
  const [exporting, setExporting] = useState(false);

  const reportContext = useMemo(() => {
    const dataset = data?.dataset || {};
    const clean = data?.cleaning_report || {};
    const topPairs = data?.correlations?.top_pairs || [];
    const insights = data?.insights || {};

    return {
      dataset,
      clean,
      topPairs,
      insights,
    };
  }, [data]);

  const exportPdf = async () => {
    setExporting(true);
    try {
      const doc = new jsPDF({ unit: "mm", format: "a4" });

      doc.setFillColor(11, 18, 32);
      doc.rect(0, 0, 210, 297, "F");

      doc.setTextColor(95, 180, 255);
      doc.setFontSize(26);
      doc.text("Insight", 20, 22);

      doc.setTextColor(200, 210, 230);
      doc.setFontSize(11);
      doc.text("AI-Powered Data Analysis Report", 20, 30);
      doc.text(`Analysis ID: ${data.analysis_id}`, 20, 36);

      doc.setDrawColor(45, 65, 100);
      doc.line(20, 40, 190, 40);

      const dataset = reportContext.dataset;
      const clean = reportContext.clean;
      const topPairs = reportContext.topPairs;
      const insights = reportContext.insights;

      doc.setFontSize(14);
      doc.setTextColor(230, 235, 245);
      doc.text("Dataset KPI Summary", 20, 50);

      const kpis = [
        ["Rows", String(dataset.rows || 0)],
        ["Columns", String(dataset.columns || 0)],
        ["Numeric Features", String((dataset.numeric_columns || []).length)],
        ["Categorical Features", String((dataset.categorical_columns || []).length)],
        ["Duplicates Removed", String(clean.duplicates_removed || 0)],
        ["Missing Fixed", String((clean.missing_before || 0) - (clean.missing_after || 0))],
      ];

      let y = 58;
      kpis.forEach(([k, v], i) => {
        const x = i % 2 === 0 ? 20 : 110;
        if (i % 2 === 0 && i > 0) y += 12;
        doc.setFillColor(20, 30, 50);
        doc.roundedRect(x, y, 80, 10, 2, 2, "F");
        doc.setTextColor(170, 180, 205);
        doc.setFontSize(9);
        doc.text(k, x + 3, y + 4);
        doc.setTextColor(120, 210, 255);
        doc.setFontSize(11);
        doc.text(v, x + 3, y + 8);
      });

      let textY = 102;
      textY = createCorrelationBars(doc, topPairs, textY + 2) + 6;

      doc.setTextColor(230, 235, 245);
      doc.setFontSize(13);
      doc.text("Executive Summary", 20, textY);
      doc.setTextColor(200, 210, 230);
      doc.setFontSize(10);
      textY = addWrappedText(doc, insights.executive_summary || "No summary generated.", 20, textY + 6, 170, 4.5) + 4;

      doc.setTextColor(230, 235, 245);
      doc.setFontSize(13);
      doc.text("Recommendations", 20, textY);
      doc.setTextColor(200, 210, 230);
      doc.setFontSize(10);

      (insights.recommendations || ["No recommendations available."]).slice(0, 6).forEach((rec, idx) => {
        textY = addWrappedText(doc, `${idx + 1}. ${rec}`, 24, textY + 6, 166, 4.5);
      });

      doc.setTextColor(140, 150, 170);
      doc.setFontSize(8);
      doc.text("Generated by Insight", 20, 289);

      doc.save(`insight_report_${data.analysis_id}.pdf`);
    } finally {
      setExporting(false);
    }
  };

  if (!data) return null;

  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-br from-dark-800 to-dark-900 rounded-xl p-6 border border-dark-700">
        <h2 className="text-2xl font-bold flex items-center gap-3">
          <FileText className="text-blue-400" size={28} />
          Reports
        </h2>
        <p className="text-gray-400 mt-2">Generate a polished PDF report including summary, KPIs, correlation chart bars, and recommendations.</p>
      </div>

      <div className="bg-gradient-to-br from-dark-800 to-dark-900 rounded-xl p-6 border border-dark-700">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
          <div className="bg-dark-700/40 rounded-lg p-4 border border-dark-600">
            <p className="text-xs uppercase tracking-wide text-gray-400">Rows</p>
            <p className="text-2xl font-bold text-cyan-400 mt-1">{data?.dataset?.rows || 0}</p>
          </div>
          <div className="bg-dark-700/40 rounded-lg p-4 border border-dark-600">
            <p className="text-xs uppercase tracking-wide text-gray-400">Columns</p>
            <p className="text-2xl font-bold text-blue-400 mt-1">{data?.dataset?.columns || 0}</p>
          </div>
          <div className="bg-dark-700/40 rounded-lg p-4 border border-dark-600">
            <p className="text-xs uppercase tracking-wide text-gray-400">Top Correlations</p>
            <p className="text-2xl font-bold text-purple-400 mt-1">{data?.correlations?.top_pairs?.length || 0}</p>
          </div>
          <div className="bg-dark-700/40 rounded-lg p-4 border border-dark-600">
            <p className="text-xs uppercase tracking-wide text-gray-400">Duplicates Removed</p>
            <p className="text-2xl font-bold text-yellow-400 mt-1">{data?.cleaning_report?.duplicates_removed || 0}</p>
          </div>
        </div>

        <button
          onClick={exportPdf}
          disabled={exporting}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 disabled:opacity-60 text-white transition-colors"
        >
          {exporting ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
          {exporting ? "Generating PDF..." : "Export PDF Report"}
        </button>
      </div>
    </div>
  );
}
